### ISSUE TITLE
Reverse image search

### ISSUE THREAD

**Issue by Donkey-Doug** [zhanghai/TextSelectionWebSearch#5]
I know this is beyond the functionality of the app, but it would be really cool if you could add the option to share an image with this app and then it would reverse image search it in my default browser.

**Comment by zhanghai** [comment]
This is the functionality that's enough to be another app. I'm personally using [Image Search](https://play.google.com/store/apps/details?id=rikka.searchbyimage2) by [@RikkaW](https://github.com/RikkaW/SearchByImage) and it worked well for me.

**Comment by internet-coffee** [comment]
Hi @Donkey-Doug ,you can try my app. https://github.com/kevin970712/PicSearch
