### ISSUE TITLE
[Feature request] Add more than 1 search engine to the toolbar

### ISSUE THREAD

**Issue by Iz-zzzzz** [zhanghai/TextSelectionWebSearch#6]
Add more than 1 search engine to the toolbar. For example, I can add both Google search and Bing search button to the toolbar. And let the user modify the button name, too. Hence, users can choose what search engine to want to use while selecting text.

**Comment by zhanghai** [comment]
Unfortunately that's not possible - the names in the toolbar has to be statically baked in the APK, which is an Android restriction.

**Comment by Iz-zzzzz** [comment]
At least please change the button name to something else like "Selection to search". There are 2 "Web search" buttons, one is the browser's(or maybe system idk), another one is this app's.
![tempFileForShare_20231003-212337](https://github.com/zhanghai/TextSelectionWebSearch/assets/57972212/2ed45995-970f-4976-9342-3814aba2b975)

**Comment by zhanghai** [comment]
They are indeed basically the same action, so they should be named the same. When there are two, the first one should be your browser's and that only happens in your browser app, so just always use the first one.
